### ISSUE TITLE
Move persistent disk logic from Lima to alpine-lima

### ISSUE THREAD

**Issue by jandubois** [lima-vm/alpine-lima#131]
_Moving this to a new issue because I want to close #123_

I assume you mean the cidata boot scripts and not the logic in Go here.

I think some of the logic (like `04-persistent-data-volume`) should be moved to the distro instead of being hard-coded in Lima (e.g. I sometimes wanted an Alpine VM without the persistent disk).

This wasn't possible originally, but I think we have most of the pieces in place to implement something like

```yaml
additionalDisks:
- name: data
  internal: true

provision:
- mode: boot
  script: lima-setup-peristent-disk /etc /home /root /tmp /usr/local /var/lib
```

The `internal: true` setting would create a non-shared additional disk that would be created and deleted automatically as the instance is created/deleted.

And we would need to implement `mode: boot` support for Alpine.

Then the script can be included in the ISO and you can have templates with and without persistent disks, and could even configure which directories you want to persist.

We would still have to keep the current boot scripts for backwards compatibility with older existing instances, so we would also need a mechanism to disable the builtin support.

_Originally posted by @jandubois in https://github.com/lima-vm/alpine-lima/issues/123#issuecomment-1986095900_
