### ISSUE TITLE
Create edition with nerdctl installed

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/alpine-lima#34]
From https://github.com/lima-vm/lima/issues/489

https://github.com/lima-vm/lima/blob/master/examples/alpine.yaml

```yaml

containerd:
  system: false
  user: false
```

The lima nerdctl provisioning doesn't work without systemd installed

* https://github.com/lima-vm/lima/issues/310

----

One approach would be to create a separate ISO, with containerd installed.

And then add nerdctl and buildctl/buildkitd from the nerdctl-full tarball, like lima.

**Comment by afbjorklund** [comment]
Apparently it is **not** possible to use containerd from nerdctl, so use apk instead:

![alpine-nerdctl-containerd](https://user-images.githubusercontent.com/10364051/147964000-6acc5615-d43c-45de-a024-471249d5816d.png)

**Comment by afbjorklund** [comment]
Here is a nice soundtrack, while building the image: https://www.youtube.com/watch?v=WKSFmP_16V0

**Comment by afbjorklund** [comment]
```
51M	iso/alpine-lima-std-3.14.3-x86_64.iso
100M	iso/alpine-lima-nc-3.14.3-x86_64.iso
```

**Comment by afbjorklund** [comment]
Contributing buildkit to alpine as an apk would be a nice future improvement.

https://git.alpinelinux.org/aports/tree/community/containerd?h=3.14-stable

**Comment by afbjorklund** [comment]
Think I also need to install cni-plugins, because they're in the wrong path.

**Comment by afbjorklund** [comment]
I still want to make the "regular" containerd installation work (for "system"), but this "nc" ISO could be a workaround/optimization.


```yaml
images:
- location: https://github.com/lima-vm/alpine-lima/releases/download/v0.2.2/alpine-lima-std-3.14.3-x86_64.iso
  arch: "x86_64"
  digest: "sha512:573964991fb135aac18e44c444c1c924cd6110d4c823e887451e134adbecd7abb98bb84d22872cec1c9ed5b2cd9d87f664817adb15938ca3a69a9a2c70d66837"
- location: https://github.com/lima-vm/alpine-lima/releases/download/v0.2.2/alpine-lima-std-3.14.3-aarch64.iso
  arch: "aarch64"
  digest: "sha512:6ff651023fbc4ec56c437124392d29cfa8eb8fe6d34c0e797b85b21734a6629aec38226c298f475b9ed63bef7664d49ba1bd5adc667c621efd7aa43e7020cc27"

containerd:
  system: true
  user: false
```

```yaml
images:
- location: https://github.com/lima-vm/alpine-lima/releases/download/v0.2.x/alpine-lima-nc-3.14.3-x86_64.iso
  arch: "x86_64"
- location: https://github.com/lima-vm/alpine-lima/releases/download/v0.2.x/alpine-lima-nc-3.14.3-aarch64.iso
  arch: "aarch64"

containerd:
  system: false
  user: false
```

**Comment by afbjorklund** [comment]
Note: I set buildkitd to use the containerd worker, so I don't _think_ it needs the CNI plugins by itself (for OCI worker) ?

`--oci-worker=false --containerd-worker=true`

And I don't think nerdctl needs it either, but please correct me if I am wrong - then we could try some other approach.

**Comment by afbjorklund** [comment]
Note: the versions for docker and podman were _much_ easier to do, because of proper apk packaging.

Once nerdctl (and containerd and buildkit) are also available in Alpine, this would become trivial too.

**Comment by jandubois** [comment]
Maybe we (you?) should submit the packages for upstream first, and we delay this PR until they are available?

Or do you need this image rather "sooner"?

**Comment by afbjorklund** [comment]
> Or do you need this image rather "sooner"?

There is no rush, I think one can use the current (std) alpine image and do the install from there if in a hurry.

I'm not even sure if all these (well, three) images should be built by default, or if they are just "examples" ?
Although it will be hard to link to them if they are not built and checksummed and provided automatically.

```yaml
images:
- location: https://github.com/lima-vm/alpine-lima/releases/download/v0.2.2/alpine-lima-std-3.14.3-x86_64.iso
  arch: "x86_64"
  digest: "sha512:573964991fb135aac18e44c444c1c924cd6110d4c823e887451e134adbecd7abb98bb84d22872cec1c9ed5b2cd9d87f664817adb15938ca3a69a9a2c70d66837"
- location: https://github.com/lima-vm/alpine-lima/releases/download/v0.2.2/alpine-lima-std-3.14.3-aarch64.iso
  arch: "aarch64"
  digest: "sha512:6ff651023fbc4ec56c437124392d29cfa8eb8fe6d34c0e797b85b21734a6629aec38226c298f475b9ed63bef7664d49ba1bd5adc667c621efd7aa43e7020cc27"
```

It was just that the current "alpine.yaml" example doesn't work (for nerdctl), and that was a bit disappointing...

And with both `docker-machine` and `podman-machine` being deprecated, there were no lightweight alternatives.
One would have to go full Docker Desktop (LinuxKit) or Podman Desktop (CoreOS), to run them on Mac or Win.

* ~~https://github.com/boot2docker/boot2docker~~
* ~~https://github.com/boot2podman/boot2podman~~

But it (`containerd: `) can be fixed in limactl, as well.

These lima ISO images were just an "optimization".
